In [2]:
import numpy as np

In [3]:
np.random.randint(0,10,15)

array([6, 3, 6, 3, 9, 2, 6, 5, 4, 9, 4, 3, 0, 4, 5])

In [11]:
a = np.random.randint(0,10, (3,5))

In [10]:
a.sum(axis = 0, keepdims = True)

array([[ 9, 16, 13, 10, 12]])

In [12]:
b = np.random.randn(10).reshape(2,5)

In [13]:
b

array([[-0.01992397,  0.26001035, -0.62618461, -0.35078983,  0.78653118],
       [ 0.30968716,  0.94991443,  0.57600069, -0.38028564,  0.35475091]])

In [14]:
b.mean()

0.18597106752488243

In [15]:
b.std()

0.4956236142671009